Translate using AWS Translate

diff --git a/execute b/execute
--- a/execute
+++ b/execute
@@ -2,18 +2,55 @@
 
 BUCKET_NAME=saddleback-translations
 VIDEO_FILE_PATH=./input/a.mp4
-AUDIO_FILE_PATH=./output/a.mp3
+AUDIO_FILE_NAME=a.mp3
+AUDIO_FILE_PATH="./output/$AUDIO_FILE_NAME"
+UPLOADED_AUDIO_FILE_PATH="input/$AUDIO_FILE_NAME"
+TRANSCRIPTION_FILE_NAME="input/transcriptions/a.json"
 
 ./create_bucket $BUCKET_NAME
 
-if [ $? -nq 0 ]; then
+if [ $? -eq 0 ]; then
+    echo "Bucket created successfully."
+else
     echo "Error: Failed to create the bucket."
     exit 1
 fi
 
 # extract audio from video
 ./extract $VIDEO_FILE_PATH $AUDIO_FILE_PATH
-if [ $? -nq 0 ]; then
+if [ $? -eq 0 ]; then
+    echo "Audio extracted successfully."
+else
     echo "Error: Failed to extract audio from video."
     exit 1
 fi
+
+# upload the audio file to the bucket
+./upload $AUDIO_FILE_PATH $BUCKET_NAME $UPLOADED_AUDIO_FILE_PATH
+if [ $? -eq 0 ]; then
+    echo "Audio uploaded successfully."
+else
+    echo "Error: Failed to upload audio."
+    exit 1
+fi
+
+# transcript the audio file
+./transcribe $UPLOADED_AUDIO_FILE_PATH $TRANSCRIPTION_FILE_NAME $BUCKET_NAME
+if [ $? -eq 0 ]; then
+    echo "Audio transcribed successfully."
+else
+    echo "Error: Failed to transcribe audio."
+    exit 1
+fi
+
+# download the transcription file
+./download $TRANSCRIPTION_FILE_NAME $BUCKET_NAME
+
+# extract the transcription from JSON into text
+./transform ./input/transcriptions/a.json ./input/translations/en.txt
+
+# upload the translation text to the bucket
+./upload ./input/translations/en.txt $BUCKET_NAME input/translations/en.txt
+
+# translate the text
+./translate input/translations/en.txt $BUCKET_NAME
